project:
  type: website
  output-dir: docs # for GitHub Pages
  resources:
    - template/
    - template/h-UQTR-r.png
  render:
    - "*.qmd"
    - "!classroom/"
  

website:
  title: "PRO1036"
  favicon: template/programming-icon.png
  
  page-footer: 
    left: "Fait avec ❤️ et [Quarto](https://quarto.org/)."
    center:
      - text: "À propos"
        href: about.qmd
    right:
      - text: <img src="https://licensebuttons.net/l/by-sa/4.0/88x31.png" alt="Creative Commons License" style="border-width:0"/>
        href: https://creativecommons.org/licenses/by-sa/4.0/
      - text: "Licence CC BY-SA 4.0"
        href: license.md
        
  navbar:
    logo: template/h-uqtr-r.png
    search: true
    collapse: true
    left:
      - href: index.qmd
        text: Home
      - href: cours/cours.qmd
        text: Cours
      - text: Démos
        menu:
          - href: demo/unvotes/unvotes.qmd
            text: UN votes
          - href: https://github.com/PRO1036/star-wars
            text: Star Wars
      - text: Labs
        menu:
          - href: labs/lab01-pet-names/lab01-pet-names.qmd
            text: Lab 01 - Pet names
          - href: labs/lab02-plastic-waste/lab02-plastic-waste.qmd
            text: Lab 02 - Plastic waste

      - href: ressources.qmd
        text: Ressources
      - about.qmd
  

format:
  html:
    theme: 
      - sandstone
      - template/website-uqtr.scss

    toc: true

bibliography: template/references.bib
csl: template/apa-fr.csl